/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.obeonetwork.dsl.bpmn2.validation;

import org.eclipse.emf.common.util.EList;
import org.obeonetwork.dsl.bpmn2.Artifact;
import org.obeonetwork.dsl.bpmn2.Choreography;
import org.obeonetwork.dsl.bpmn2.ConversationAssociation;
import org.obeonetwork.dsl.bpmn2.ConversationLink;
import org.obeonetwork.dsl.bpmn2.ConversationNode;
import org.obeonetwork.dsl.bpmn2.CorrelationKey;
import org.obeonetwork.dsl.bpmn2.MessageFlow;
import org.obeonetwork.dsl.bpmn2.MessageFlowAssociation;
import org.obeonetwork.dsl.bpmn2.Participant;
import org.obeonetwork.dsl.bpmn2.ParticipantAssociation;

/**
 * A sample validator interface for {@link org.obeonetwork.dsl.bpmn2.Collaboration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CollaborationValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateIsClosed(boolean value);

	boolean validateChoreographyRef(EList<Choreography> value);

	boolean validateArtifacts(EList<Artifact> value);

	boolean validateParticipantAssociations(EList<ParticipantAssociation> value);

	boolean validateMessageFlowAssociations(EList<MessageFlowAssociation> value);

	boolean validateConversationAssociations(ConversationAssociation value);

	boolean validateParticipants(EList<Participant> value);

	boolean validateMessageFlows(EList<MessageFlow> value);

	boolean validateCorrelationKeys(EList<CorrelationKey> value);

	boolean validateConversations(EList<ConversationNode> value);

	boolean validateConversationLinks(EList<ConversationLink> value);
}
