dist: trusty 
language: java
env:
  global:
  - DISPLAY=:99.0
  - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2048m -Xms1024m"
jdk:
- oraclejdk8
sudo: false
install: true
before_script:
- export SWT_GTK3=0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x16"
- sh -e /etc/init.d/xvfb start
- sleep 10
script:
- mvn clean verify
- if [[ "$TRAVIS_TAG" != "" ]]; then chmod a+x prepare-deploy-local-dir.sh && ./prepare-deploy-local-dir.sh
  $TRAVIS_BUILD_DIR/$TRAVIS_TAG; fi
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: obeo-bpmndesigner-releases
  local-dir: "${TRAVIS_BUILD_DIR}/${TRAVIS_TAG}"
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  upload-dir: ${TRAVIS_TAG}
  on:
    tags: true
    all_branches: true
    repo: ObeoNetwork/BPMN-Designer
    

cache:
  directories:
  - $HOME/.m2
