/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.dd.di.validation;

import org.eclipse.dd.di.DiagramElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.dd.di.Plane}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlaneValidator {
    boolean validate();

    boolean validatePlaneElement(EList<DiagramElement> value);
}
