/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import org.eclipse.bpmn2.AdHocOrdering;
import org.eclipse.bpmn2.Expression;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.AdHocSubProcess}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AdHocSubProcessValidator {
    boolean validate();

    boolean validateCompletionCondition(Expression value);

    boolean validateOrdering(AdHocOrdering value);

    boolean validateCancelRemainingInstances(boolean value);
}
