/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import org.eclipse.bpmn2.Lane;
import org.eclipse.bpmn2.SequenceFlow;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.FlowNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FlowNodeValidator {
    boolean validate();

    boolean validateOutgoing(EList<SequenceFlow> value);

    boolean validateIncoming(EList<SequenceFlow> value);

    boolean validateLanes(EList<Lane> value);
}
