/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import org.eclipse.bpmn2.DataInput;
import org.eclipse.bpmn2.OutputSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.InputSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputSetValidator {
    boolean validate();

    boolean validateName(String value);

    boolean validateDataInputRefs(EList<DataInput> value);

    boolean validateOptionalInputRefs(EList<DataInput> value);

    boolean validateWhileExecutingInputRefs(EList<DataInput> value);

    boolean validateOutputSetRefs(EList<OutputSet> value);
}
