/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import org.eclipse.bpmn2.EndPoint;
import org.eclipse.bpmn2.Interface;
import org.eclipse.bpmn2.ParticipantMultiplicity;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.Participant}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParticipantValidator {
    boolean validate();

    boolean validateName(String value);

    boolean validateInterfaceRefs(EList<Interface> value);

    boolean validateParticipantMultiplicity(ParticipantMultiplicity value);

    boolean validateEndPointRefs(EList<EndPoint> value);

    boolean validateProcessRef(org.eclipse.bpmn2.Process value);
}
