/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import org.eclipse.bpmn2.Artifact;
import org.eclipse.bpmn2.Auditing;
import org.eclipse.bpmn2.Collaboration;
import org.eclipse.bpmn2.CorrelationSubscription;
import org.eclipse.bpmn2.Monitoring;
import org.eclipse.bpmn2.ProcessType;
import org.eclipse.bpmn2.Property;
import org.eclipse.bpmn2.ResourceRole;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.Process}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessValidator {
    boolean validate();

    boolean validateProcessType(ProcessType value);

    boolean validateIsClosed(boolean value);

    boolean validateAuditing(Auditing value);

    boolean validateMonitoring(Monitoring value);

    boolean validateProperties(EList<Property> value);

    boolean validateSupports(EList<org.eclipse.bpmn2.Process> value);

    boolean validateDefinitionalCollaborationRef(Collaboration value);

    boolean validateIsExecutable(boolean value);

    boolean validateResources(EList<ResourceRole> value);

    boolean validateArtifacts(EList<Artifact> value);

    boolean validateCorrelationSubscriptions(EList<CorrelationSubscription> value);
}
