/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import org.eclipse.bpmn2.DataInput;
import org.eclipse.bpmn2.DataInputAssociation;
import org.eclipse.bpmn2.EventDefinition;
import org.eclipse.bpmn2.InputSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.ThrowEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ThrowEventValidator {
    boolean validate();

    boolean validateInputSet(InputSet value);

    boolean validateEventDefinitionRefs(EList<EventDefinition> value);

    boolean validateDataInputAssociation(EList<DataInputAssociation> value);

    boolean validateDataInputs(EList<DataInput> value);

    boolean validateEventDefinitions(EList<EventDefinition> value);
}
