/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.obeonetwork.dsl.bpmn2.validation;

import org.eclipse.emf.common.util.EList;

import org.obeonetwork.dsl.bpmn2.Artifact;
import org.obeonetwork.dsl.bpmn2.Auditing;
import org.obeonetwork.dsl.bpmn2.Collaboration;
import org.obeonetwork.dsl.bpmn2.CorrelationSubscription;
import org.obeonetwork.dsl.bpmn2.Monitoring;
import org.obeonetwork.dsl.bpmn2.ProcessType;
import org.obeonetwork.dsl.bpmn2.Property;
import org.obeonetwork.dsl.bpmn2.ResourceRole;

/**
 * A sample validator interface for {@link org.obeonetwork.dsl.bpmn2.Process}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessValidator {
	boolean validate();

	boolean validateProcessType(ProcessType value);

	boolean validateIsClosed(boolean value);

	boolean validateAuditing(Auditing value);

	boolean validateMonitoring(Monitoring value);

	boolean validateProperties(EList<Property> value);

	boolean validateSupports(EList<org.obeonetwork.dsl.bpmn2.Process> value);

	boolean validateDefinitionalCollaborationRef(Collaboration value);

	boolean validateIsExecutable(boolean value);

	boolean validateResources(EList<ResourceRole> value);

	boolean validateArtifacts(EList<Artifact> value);

	boolean validateCorrelationSubscriptions(
			EList<CorrelationSubscription> value);
}
