/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.obeonetwork.dsl.dd.dc.validation;

/**
 * A sample validator interface for {@link org.obeonetwork.dsl.dd.dc.Font}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FontValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateSize(float value);

	boolean validateIsBold(boolean value);

	boolean validateIsItalic(boolean value);

	boolean validateIsUnderline(boolean value);

	boolean validateIsStrikeThrough(boolean value);
}
