/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.obeonetwork.dsl.bpmn2.validation;

import org.eclipse.emf.common.util.EList;
import org.obeonetwork.dsl.bpmn2.BoundaryEvent;
import org.obeonetwork.dsl.bpmn2.DataInputAssociation;
import org.obeonetwork.dsl.bpmn2.DataOutputAssociation;
import org.obeonetwork.dsl.bpmn2.InputOutputSpecification;
import org.obeonetwork.dsl.bpmn2.LoopCharacteristics;
import org.obeonetwork.dsl.bpmn2.Property;
import org.obeonetwork.dsl.bpmn2.ResourceRole;
import org.obeonetwork.dsl.bpmn2.SequenceFlow;

/**
 * A sample validator interface for {@link org.obeonetwork.dsl.bpmn2.Activity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityValidator {
	boolean validate();

	boolean validateIsForCompensation(boolean value);

	boolean validateLoopCharacteristics(LoopCharacteristics value);

	boolean validateResources(EList<ResourceRole> value);

	boolean validateDefault(SequenceFlow value);

	boolean validateProperties(EList<Property> value);

	boolean validateIoSpecification(InputOutputSpecification value);

	boolean validateBoundaryEventRefs(EList<BoundaryEvent> value);

	boolean validateDataInputAssociations(EList<DataInputAssociation> value);

	boolean validateDataOutputAssociations(EList<DataOutputAssociation> value);

	boolean validateStartQuantity(int value);

	boolean validateCompletionQuantity(int value);
}
