/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.obeonetwork.dsl.bpmn2.validation;

import org.eclipse.emf.common.util.EList;
import org.obeonetwork.dsl.bpmn2.Documentation;
import org.obeonetwork.dsl.bpmn2.ExtensionAttributeValue;
import org.obeonetwork.dsl.bpmn2.ExtensionDefinition;

/**
 * A sample validator interface for {@link org.obeonetwork.dsl.bpmn2.BaseElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BaseElementValidator {
	boolean validate();

	boolean validateId(String value);

	boolean validateExtensionDefinitions(EList<ExtensionDefinition> value);

	boolean validateExtensionValues(EList<ExtensionAttributeValue> value);

	boolean validateDocumentation(EList<Documentation> value);
}
