/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.obeonetwork.dsl.bpmn2.validation;

import org.obeonetwork.dsl.bpmn2.CorrelationProperty;
import org.obeonetwork.dsl.bpmn2.FormalExpression;

/**
 * A sample validator interface for {@link org.obeonetwork.dsl.bpmn2.CorrelationPropertyBinding}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CorrelationPropertyBindingValidator {
	boolean validate();

	boolean validateDataPath(FormalExpression value);

	boolean validateCorrelationPropertyRef(CorrelationProperty value);
}
