/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.obeonetwork.dsl.bpmn2.validation;

import org.eclipse.emf.common.util.EList;

import org.obeonetwork.dsl.bpmn2.EndPoint;
import org.obeonetwork.dsl.bpmn2.Interface;
import org.obeonetwork.dsl.bpmn2.ParticipantMultiplicity;

/**
 * A sample validator interface for {@link org.obeonetwork.dsl.bpmn2.Participant}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParticipantValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateInterfaceRefs(EList<Interface> value);

	boolean validateParticipantMultiplicity(ParticipantMultiplicity value);

	boolean validateEndPointRefs(EList<EndPoint> value);

	boolean validateProcessRef(org.obeonetwork.dsl.bpmn2.Process value);
}
