/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.obeonetwork.dsl.bpmn2.validation;

import org.eclipse.emf.common.util.EList;
import org.obeonetwork.dsl.bpmn2.DataInput;
import org.obeonetwork.dsl.bpmn2.DataInputAssociation;
import org.obeonetwork.dsl.bpmn2.EventDefinition;
import org.obeonetwork.dsl.bpmn2.InputSet;

/**
 * A sample validator interface for {@link org.obeonetwork.dsl.bpmn2.ThrowEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ThrowEventValidator {
	boolean validate();

	boolean validateInputSet(InputSet value);

	boolean validateEventDefinitionRefs(EList<EventDefinition> value);

	boolean validateDataInputAssociation(EList<DataInputAssociation> value);

	boolean validateDataInputs(EList<DataInput> value);

	boolean validateEventDefinitions(EList<EventDefinition> value);
}
